---
title: "China Clinical Trial Trend"
# author: "Yubo Xiao/EDCP"
# date: "2019/7/9"

output:
  html_document: 
    code_folding: hide
    # df_print: paged
---

*dMed EDCP 11-Jul-2019*


```{r setup, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(tibble)
library(stringr)
library(ggplot2)
library(plotly)

knitr::opts_chunk$set(out.width='950px', dpi=200)
```



# {.tabset .tabset-fade .tabset-pills}

## 生物制品&化学药物 in Phase I & II & III
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds") %>% filter(drug %in% c("生物制品", "化学药物"))

Year <- summary(final$dt) %>% names()

PH1 <- filter(final, phase == "I期")
PH1num <- summary(PH1$dt)

PH2 <- filter(final, phase == "II期")
PH2num <- summary(PH2$dt)

PH3 <- filter(final, phase == "III期")
PH3num <- summary(PH3$dt)

data <- tibble(Year, PH1num, PH2num, PH3num)


cPH1num <- '#246a99'
cPH2num <- '#2e88c5'
cPH3num <- '#85c1e9'
# cPH1num <- '4285F4'
# cPH2num <- 'FBBC05'
# cPH3num <- 'EA4335'

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1num, name = 'I期',type = "bar",
            text = ~PH1num, textposition = 'inside',
            marker = list(color = cPH1num, opacity=0.9)) %>% 
  add_trace(y = ~PH2num, name = 'II期',type = "bar",
            text = ~PH2num, textposition = 'inside',
            marker = list(color = cPH2num, opacity=0.9)) %>%
  add_trace(y = ~PH3num, name = 'III期',type = "bar",
            text = ~PH3num, textposition = 'inside',
            marker = list(color = cPH3num, opacity=0.9)) %>%
  # add_text(textfont = t, textposition = "top center") %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```



<!-- ## IND&BE/BA in Phase I -->
<!-- ```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2} -->

<!-- final <- readRDS("PlotTrend.rds") -->

<!-- Year <- summary(final$dt) %>% names() -->

<!-- IND <- filter(final, phase == "I期", type == "创新药") -->
<!-- INDnum <- summary(IND$dt) -->

<!-- BEBA <- filter(final, phase == "I期", str_sub(type,1,4) == "生物等效") -->
<!-- BEBAnum <- summary(BEBA$dt) -->

<!-- data <- tibble(Year, INDnum, BEBAnum) -->


<!-- cIND <- 'rgb(49,130,189)' -->
<!-- cBEBA <- 'rgb(204,204,204)' -->
<!-- # cIND <- '#60A1F0' -->
<!-- # cBEBA <- '#00CC2C' -->
<!-- # cIND <- '#396090' -->
<!-- # cBEBA <- '#9C9C9C' -->

<!-- p <- plot_ly(data, x = ~Year) %>% -->
<!--   add_trace(y = ~INDnum, name = 'IND',type = "bar", -->
<!--             text = ~INDnum, textposition = 'inside', -->
<!--             marker = list(color = cIND, opacity=0.9)) %>%  -->
<!--   add_trace(y = ~BEBAnum, name = 'BE/BA',type = "bar", -->
<!--             text = ~BEBAnum, textposition = 'inside', -->
<!--             marker = list(color = cBEBA, opacity=0.9)) %>% -->
<!--   layout(yaxis = list(title = 'Count'), barmode = 'stack', -->
<!--          xaxis = list(title = "", tickangle = -45)) -->

<!-- p -->
<!-- ``` -->



## 生物制品&化学药物 in Phase I
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds")

Year <- summary(final$dt) %>% names()

PH1drug01 <- filter(final, phase == "I期", drug == "化学药物")
PH1drug01num <- summary(PH1drug01$dt)

PH1drug02 <- filter(final, phase == "I期", drug == "生物制品")
PH1drug02num <- summary(PH1drug02$dt)

data <- tibble(Year, PH1drug01num, PH1drug02num)

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1drug01num, name = '化学药物',type = "bar",
            text = ~PH1drug01num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  add_trace(y = ~PH1drug02num, name = '生物制品',type = "bar",
            text = ~PH1drug02num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```


# 


# {.tabset .tabset-fade .tabset-pills}


## 生物制品&化学药物&中药/天然药物 in Phase I & II & III
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds") %>% filter(drug != "其他")

Year <- summary(final$dt) %>% names()

PH1 <- filter(final, phase == "I期")
PH1num <- summary(PH1$dt)

PH2 <- filter(final, phase == "II期")
PH2num <- summary(PH2$dt)

PH3 <- filter(final, phase == "III期")
PH3num <- summary(PH3$dt)

data <- tibble(Year, PH1num, PH2num, PH3num)


cPH1num <- '#246a99'
cPH2num <- '#2e88c5'
cPH3num <- '#85c1e9'
# cPH1num <- '4285F4'
# cPH2num <- 'FBBC05'
# cPH3num <- 'EA4335'

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1num, name = 'I期',type = "bar",
            text = ~PH1num, textposition = 'inside',
            marker = list(color = cPH1num, opacity=0.9)) %>% 
  add_trace(y = ~PH2num, name = 'II期',type = "bar",
            text = ~PH2num, textposition = 'inside',
            marker = list(color = cPH2num, opacity=0.9)) %>%
  add_trace(y = ~PH3num, name = 'III期',type = "bar",
            text = ~PH3num, textposition = 'inside',
            marker = list(color = cPH3num, opacity=0.9)) %>%
  # add_text(textfont = t, textposition = "top center") %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```


## 生物制品&化学药物&中药/天然药物 in Phase I
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds")

Year <- summary(final$dt) %>% names()

PH1drug01 <- filter(final, phase == "I期", drug == "化学药物")
PH1drug01num <- summary(PH1drug01$dt)

PH1drug02 <- filter(final, phase == "I期", drug == "生物制品")
PH1drug02num <- summary(PH1drug02$dt)

PH1drug03 <- filter(final, phase == "I期", drug == "中药/天然药物")
PH1drug03num <- summary(PH1drug03$dt)

data <- tibble(Year, PH1drug01num, PH1drug02num, PH1drug03num)

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1drug01num, name = '化学药物',type = "bar",
            text = ~PH1drug01num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%  
  add_trace(y = ~PH1drug02num, name = '生物制品',type = "bar",
            text = ~PH1drug02num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  add_trace(y = ~PH1drug03num, name = '中药/天然药物',type = "bar",
            text = ~PH1drug03num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```

## 生物制品&化学药物&中药/天然药物 in Phase II
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds")

Year <- summary(final$dt) %>% names()

PH2drug01 <- filter(final, phase == "II期", drug == "化学药物")
PH2drug01num <- summary(PH2drug01$dt)

PH2drug02 <- filter(final, phase == "II期", drug == "生物制品")
PH2drug02num <- summary(PH2drug02$dt)

PH2drug03 <- filter(final, phase == "II期", drug == "中药/天然药物")
PH2drug03num <- summary(PH2drug03$dt)

data <- tibble(Year, PH2drug01num, PH2drug02num, PH2drug03num)

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH2drug01num, name = '化学药物',type = "bar",
            text = ~PH2drug01num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%  
  add_trace(y = ~PH2drug02num, name = '生物制品',type = "bar",
            text = ~PH2drug02num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  add_trace(y = ~PH2drug03num, name = '中药/天然药物',type = "bar",
            text = ~PH2drug03num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```

## 生物制品&化学药物&中药/天然药物 in Phase III
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds")

Year <- summary(final$dt) %>% names()

PH3drug01 <- filter(final, phase == "III期", drug == "化学药物")
PH3drug01num <- summary(PH3drug01$dt)

PH3drug02 <- filter(final, phase == "III期", drug == "生物制品")
PH3drug02num <- summary(PH3drug02$dt)

PH3drug03 <- filter(final, phase == "III期", drug == "中药/天然药物")
PH3drug03num <- summary(PH3drug03$dt)

data <- tibble(Year, PH3drug01num, PH3drug02num)

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH3drug01num, name = '化学药物',type = "bar",
            text = ~PH3drug01num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%  
  add_trace(y = ~PH3drug02num, name = '生物制品',type = "bar",
            text = ~PH3drug02num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  add_trace(y = ~PH3drug03num, name = '中药/天然药物',type = "bar",
            text = ~PH3drug03num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```

## 中药/天然药物&其他 in Phase I
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

final <- readRDS("PlotTrend.rds")

Year <- summary(final$dt) %>% names()

PH1drug03 <- filter(final, phase == "I期", drug == "中药/天然药物")
PH1drug03num <- summary(PH1drug03$dt)

PH1drug04 <- filter(final, phase == "I期", drug == "其他")
PH1drug04num <- summary(PH1drug04$dt)

data <- tibble(Year, PH1drug03num, PH1drug04num)

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1drug03num, name = '中药/天然药物',type = "bar",
            text = ~PH1drug03num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%  
  add_trace(y = ~PH1drug04num, name = '其他',type = "bar",
            text = ~PH1drug04num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```


# 

# {.tabset .tabset-fade .tabset-pills}

## 生物制品&化学药物 in Phase I & II & III LOCAL
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}
final <- readRDS("comdat8164_20190710.rds") %>% 
  select("studyid", "startdt", "sponsor", "studyphase", "studytype", "drugclass", "firstsubjdt", "enddt") %>% 
  mutate(id = str_sub(studyid, 15,25),
         dt = if_else(str_sub(firstsubjdt, 15, 15) == "登",
                               str_sub(startdt, 15,24),
                               str_sub(firstsubjdt, 15,24)),
         dt = if_else(str_sub(dt,1,1)=="预",NA_character_,dt),
         dt = as.factor(str_sub(dt,1,4)),
         drug = if_else(str_sub(drugclass, 1,1) == "<",
                        "其他", drugclass),
         drug = factor(drug, levels = c("化学药物", "生物制品", "中药/天然药物", "其他")),
         phase = if_else(str_sub(studyphase,1,1) == "其",
                         "其他",studyphase),
         phase = factor(phase, levels = c("I期", "II期", "III期", "其他")),
         type = if_else(str_sub(studytype,1,4) == "生物等效",
                        studytype, "创新药"),
         sponsor = str_replace_all(sponsor, pattern = '[:digit:]', replacement = ""),
         sponsor = str_replace_all(sponsor, pattern = '[:punct:]', replacement = ""),
         sponsor = str_replace_all(sponsor, pattern = "<wt>", replacement = ""),
         sponsor = str_sub(sponsor, 1, 20)
         ) %>% 
  # filter(str_sub(firstsubjdt, 15, 15) != "登") %>% 
  select(id, dt,drug, phase, type, sponsor) %>% 
  filter(!is.na(dt), !is.na(phase)) %>%
  filter(
    is.na(str_match(string = sponsor, pattern = "辉瑞")),
    is.na(str_match(string = sponsor, pattern = "阿拉宾度")),
    is.na(str_match(string = sponsor, pattern = "阿斯利康")),
    is.na(str_match(string = sponsor, pattern = "艾尔建")),
    is.na(str_match(string = sponsor, pattern = "爱尔兰利奥制药")),
    is.na(str_match(string = sponsor, pattern = "爱尔康中国眼科")),
    is.na(str_match(string = sponsor, pattern = "安万特中国")),
    is.na(str_match(string = sponsor, pattern = "昂德生物")),
    is.na(str_match(string = sponsor, pattern = "百时美施贵宝")),
    is.na(str_match(string = sponsor, pattern = "拜耳医药")),
    is.na(str_match(string = sponsor, pattern = "诺华制药")),
    is.na(str_match(string = sponsor, pattern = "勃林格殷格翰")),
    is.na(str_match(string = sponsor, pattern = "大冢")),
    is.na(str_match(string = sponsor, pattern = "诺和诺德")),
    is.na(str_match(string = sponsor, pattern = "丹麦灵北")),
    is.na(str_match(string = sponsor, pattern = "德国柏林化学")),
    is.na(str_match(string = sponsor, pattern = "德国默克")),
    is.na(str_match(string = sponsor, pattern = "帝国制药株式会社")),
    is.na(str_match(string = sponsor, pattern = "第一三共")),
    is.na(str_match(string = sponsor, pattern = "葛兰素史克")),
    is.na(str_match(string = sponsor, pattern = "韩美药品株式会社")),
    is.na(str_match(string = sponsor, pattern = "韩国大化")),
    is.na(str_match(string = sponsor, pattern = "罗氏研发")),
    is.na(str_match(string = sponsor, pattern = "美国艾尔建")),
    is.na(str_match(string = sponsor, pattern = "美国波士顿生物")),
    is.na(str_match(string = sponsor, pattern = "美国强新生物")),
    is.na(str_match(string = sponsor, pattern = "美国英创远达")),
    is.na(str_match(string = sponsor, pattern = "默克雪兰诺")),
    is.na(str_match(string = sponsor, pattern = "默沙东研发")),
    is.na(str_match(string = sponsor, pattern = "默沙东中国")),
    is.na(str_match(string = sponsor, pattern = "日本BCG制造株式会社")),
    is.na(str_match(string = sponsor, pattern = "日本大正药品工业株式会社")),
    is.na(str_match(string = sponsor, pattern = "日本新药株式会社")),
    is.na(str_match(string = sponsor, pattern = "日东电工株式会社")),
    is.na(str_match(string = sponsor, pattern = "瑞士赫尔森")),
    is.na(str_match(string = sponsor, pattern = "赛诺菲")),
    is.na(str_match(string = sponsor, pattern = "罗氏制药")),
    is.na(str_match(string = sponsor, pattern = "强生制药")),
    is.na(str_match(string = sponsor, pattern = "施维雅天津")),
    is.na(str_match(string = sponsor, pattern = "施泰福大药厂英")),
    is.na(str_match(string = sponsor, pattern = "意大利SigmaTau制药")),
    is.na(str_match(string = sponsor, pattern = "意大利凯西制药")),
    is.na(str_match(string = sponsor, pattern = "意大利依赛特")),
    is.na(str_match(string = sponsor, pattern = "意大利凯西制药")),
    is.na(str_match(string = sponsor, pattern = "印度瑞迪博士")),
    is.na(str_match(string = sponsor, pattern = "印度太阳药业")),
    is.na(str_match(string = sponsor, pattern = "施贵宝")),
    is.na(str_match(string = sponsor, pattern = "中外制药株式会社")),
    is.na(as.vector(str_match(string = sponsor, pattern = "山德士中国制药")))
  ) %>%
  filter(drug %in% c("生物制品", "化学药物"))

final <- select(final, -"sponsor")

# saveRDS(object = final,file =  "local.rds")

Year <- summary(final$dt)[1:18] %>% names()

PH1 <- filter(final, phase == "I期")
PH1num <- summary(PH1$dt)

PH2 <- filter(final, phase == "II期")
PH2num <- summary(PH2$dt)

PH3 <- filter(final, phase == "III期")
PH3num <- summary(PH3$dt)

data <- tibble(Year, PH1num, PH2num, PH3num)


cPH1num <- '#246a99'
cPH2num <- '#2e88c5'
cPH3num <- '#85c1e9'
# cPH1num <- '4285F4'
# cPH2num <- 'FBBC05'
# cPH3num <- 'EA4335'

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1num, name = 'I期',type = "bar",
            text = ~PH1num, textposition = 'inside',
            marker = list(color = cPH1num, opacity=0.9)) %>% 
  add_trace(y = ~PH2num, name = 'II期',type = "bar",
            text = ~PH2num, textposition = 'inside',
            marker = list(color = cPH2num, opacity=0.9)) %>%
  add_trace(y = ~PH3num, name = 'III期',type = "bar",
            text = ~PH3num, textposition = 'inside',
            marker = list(color = cPH3num, opacity=0.9)) %>%
  # add_text(textfont = t, textposition = "top center") %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```


## 生物制品&化学药物 in Phase I LOCAL
```{r, message=FALSE, warning=FALSE, fig.width = 4, fig.height = 2}

# final <- readRDS("PlotTrend.rds")

Year <- summary(final$dt)[1:18] %>% names()

PH1drug01 <- filter(final, phase == "I期", drug == "化学药物")
PH1drug01num <- summary(PH1drug01$dt)

PH1drug02 <- filter(final, phase == "I期", drug == "生物制品")
PH1drug02num <- summary(PH1drug02$dt)

data <- tibble(Year, PH1drug01num, PH1drug02num)

p <- plot_ly(data, x = ~Year) %>%
  add_trace(y = ~PH1drug01num, name = '化学药物',type = "bar",
            text = ~PH1drug01num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  add_trace(y = ~PH1drug02num, name = '生物制品',type = "bar",
            text = ~PH1drug02num, textposition = 'inside',
            marker = list(opacity=0.9)) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack',
         xaxis = list(title = "", tickangle = -45))

p
```



